### ISSUE TITLE
erfc(::BigFloat) crashes Julia

### ISSUE THREAD

**Issue by dlichtistw** [JuliaMath/SpecialFunctions.jl#127] opened 2018-10-25 11:53 UTC
Julia 0.7 crashes whenever I call `SpecialFunctions.erfc` with a `BigInt` or `BigFloat` value near 30. For example `erfc(big"26.5")` and `erfc(big"32.0")` are ok, but `erfc(big"27.0")` and `erfc(big"31.5")` will fail. `BigInt`s in that range will also fail, but the corresponding `Float64` and `Int64` will succeed.

I am using `SpecialFunctions` v0.7.1 on Julia 0.7.

```julia
julia> erfc(big"30.5");
/buildworker/worker/package_linux64/build/deps/srccache/mpfr-4.0.1/src/uceil_log2.c:40: MPFR assertion failed: exp < 1023

signal (6): Aborted
in expression starting at no file:0
__libc_signal_restore_set at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
mpfr_assert_fail at /buildworker/worker/package_linux64/build/deps/srccache/mpfr-4.0.1/src/mpfr-gmp.c:300
__gmpfr_ceil_log2 at /buildworker/worker/package_linux64/build/deps/srccache/mpfr-4.0.1/src/uceil_log2.c:40
mpfr_erf at /buildworker/worker/package_linux64/build/deps/srccache/mpfr-4.0.1/src/erf.c:240
mpfr_erfc at /buildworker/worker/package_linux64/build/deps/srccache/mpfr-4.0.1/src/erfc.c:251
erfc at /home/lichti/.julia/packages/SpecialFunctions/sXbz6/src/erf.jl:15
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:428
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f98dddd9f4f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:831
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:633
eval at ./boot.jl:319
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:262
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1538 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:268
unknown function (ip: 0xffffffffffffffff)
Allocations: 735907 (Pool: 735629; Big: 278); GC: 0
Aborted (core dumped)
```

**Comment by stevengj** [comment] 2018-10-25 13:43
This is an [MPFR assertion failure](https://github.com/BrianGladman/mpfr/blob/3a80a768aaeb044888c0b0ca5f84c4ce88adacd6/src/uceil_log2.c#L40), so it looks like a bug in MPFR?

**Comment by simonbyrne** [comment] 2018-10-25 15:46
The [MPFR release notes](https://www.mpfr.org/mpfr-4.0.1/#bugs) state that they fixed a bug related to `erfc`:
> The `mpfr_erf` and `mpfr_erfc` functions can yield an assertion failure due to the fact that the error bound is computed with the double type and can overflow. This bug is fixed by the [`erf` patch](https://www.mpfr.org/mpfr-4.0.1/patch11), which also provides testcases.
> Corresponding changeset in the 4.0 branch: [12950](https://gforge.inria.fr/scm/viewvc.php/mpfr?revision=12950&view=revision).

But Julia 1.0.1 is using MPFR 4.0.1, so maybe this is different?

**Comment by stevengj** [comment] 2018-10-25 19:40
Nope, it seems like the problem is still present with Julia 1.0.1 and MPFR 4.0.1:
```jl
julia> using SpecialFunctions

julia> erfc(big"30.5")
/Users/osx/buildbot/slave/package_osx64/build/deps/srccache/mpfr-4.0.1/src/uceil_log2.c:40: MPFR assertion failed: exp < 1023
```

**Comment by simonbyrne** [comment] 2018-10-25 20:17
I don't quite understand their release notes, but it looks like those are the bugs that have been identified in the 4.0.1 release (since it seems like [patch 11](https://www.mpfr.org/mpfr-4.0.1/patch11) is _not_ in 4.0.1).

So looks like we need to wait until the next MPFR release.

**Comment by dlichtistw** [comment] 2018-12-05 09:10
Since switching to Julia 1.0.2 did not solve the problem for me either, I built my own libmpfr from subversion (revision 13311) and placed it in julia's lib directory. The result is positive.
```julia
julia> erfc(big"30")
2.564656203756111600033397277501447146548889722778617054122599586184238694779193e-393
```
So, this issue can probably be closed.

**Comment by ararslan** [comment] 2018-12-05 09:40
I think we should keep the issue open so we don't lose track of it, since we'll need to bump Julia's MPFR version when a newer one is available.

**Comment by simonbyrne** [comment] 2019-02-11 18:02
New version of MPFR has been released, see https://github.com/JuliaLang/julia/pull/31041

**Comment by oscardssmith** [comment] 2021-05-31 00:27
Fixed on master.

**Closed by oscardssmith** 2021-05-31 00:27 UTC

**Comment by giordano** [comment] 2021-05-31 00:29
master of what?  Julia?

**Comment by oscardssmith** [comment] 2021-05-31 00:57
I tested on a few day old master of Julia, with SpecialFunctions v1.4.2

**Comment by giordano** [comment] 2021-05-31 01:05
I can't reproduce with SpecialFunctions v0.7.1 on Julia v1.0.5 on linux, which is close to (but not exactly the same) the setup of the original report, so I'm not sure that the fact you can't reproduce the bug now with a recent version of Julia/SpecialFunctions means that the bug has been fixed, maybe you also couldn't reproduce it before.  But it looks like no one else has been able to reproduce it either and the OP had already a working setup 2.5 years ago, so probably not worth keeping this open anyway.
