### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by pearcemc** [JuliaMath/SpecialFunctions.jl#76] opened 2018-01-25 13:06 UTC
I am having a problem with using `digamma` on 0.6.2.

Say I have this code saved in `reproducible.jl`:

```
module ReproducibleError

using SpecialFunctions

function make_error()
  return digamma(rand(10))
end

end #module
```

When I try to call `make_error` I get the following:

```
julia> VERSION
v"0.6.2"

julia> include("/projects/juliadev/misc/reproducible.jl")
ReproducibleError

julia> ReproducibleError.make_error()
ERROR: digamma([0.00682959, 0.856906, 0.855035, 0.524282, 0.89706, 0.874412, 0.948103, 0.815427, 0.339152, 0.530628],) has been moved to the package SpecialFunctions.jl.
Run Pkg.add("SpecialFunctions") to install SpecialFunctions on Julia v0.6 and later,
and then run `using SpecialFunctions`.
Stacktrace:
 [1] make_error() at /projects/juliadev/misc/reproducible.jl:7
```

However, if I type `using SpecialFunctions` directly into the REPL I can use `digamma` just fine... in the REPL. Can't figure why the module isn't importing properly into another.

**Comment by ararslan** [comment] 2018-02-02 22:01
I actually can't even use it in the REPL.
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using SpecialFunctions

julia> digamma(rand(10))
ERROR: digamma([0.675763, 0.473888, 0.714789, 0.382325, 0.741078, 0.34093, 0.791917, 0.55993, 0.70172, 0.911172],) has been moved to the package SpecialFunctions.jl.
Run Pkg.add("SpecialFunctions") to install SpecialFunctions on Julia v0.6 and later,
and then run `using SpecialFunctions`.
Stacktrace:
 [1] digamma(::Array{Float64,1}) at ./deprecated.jl:1303
```

**Comment by stevengj** [comment] 2018-02-02 22:03
That's because you should do `digamma.(rand(10))` to operate on an array.

This is a duplicate of JuliaLang/julia#24618

**Closed by stevengj** 2018-02-02 22:03 UTC

**Comment by ararslan** [comment] 2018-02-02 22:08
Good catch, I didn't think about that. Thanks, @stevengj.
