### ISSUE TITLE
besselj(-n,0.0) throws AmosException(1)

### ISSUE THREAD

**Issue by arturgower** [JuliaMath/SpecialFunctions.jl#60] opened 2017-11-20 13:28 UTC
For integer n, we should have `besselj(-n,0.0) = 0.0 + 0.0im` instead we get:
```
besselj(-1,0.0)
Base.Math.AmosException(1)
 in _bessely(::Float64, ::Complex{Float64}, ::Int32) at ./special/bessel.jl:231
 in besselj(::Float64, ::Complex{Float64}) at ./special/bessel.jl:294
 in besselj(::Int64, ::Complex{Float64}) at ./special/bessel.jl:458
```
I believe this is a bug. 

If n is not an integer than `besselj(-n,0.0)` leads to a complex infinity, and so should probably throw an `AmosException(1)`

**Comment by musm** [comment] 2017-11-21 15:37
Seems to be working fine for me:
![image](https://user-images.githubusercontent.com/4319522/33081260-efbddaf4-cea7-11e7-9783-9449a4077ce0.png)

Maybe you need to do a `Pkg.update`

**Comment by arturgower** [comment] 2017-11-21 16:34
Right, those work for me now. But this, very similar example, still throws an error:
```julia
besselj(-1,0.0 + 0.0im)
Base.Math.AmosException(1)
 in _bessely(::Float64, ::Complex{Float64}, ::Int32) at ./special/bessel.jl:231
 in besselj(::Float64, ::Complex{Float64}) at ./special/bessel.jl:294
 in besselj(::Int64, ::Complex{Float64}) at ./special/bessel.jl:458
```
and I think it should also give `0.0 + 0.0im`.

**Comment by oscardssmith** [comment] 2021-05-31 00:29
Closing as can not reproduce on new verisons.

**Closed by oscardssmith** 2021-05-31 00:29 UTC
